### ISSUE TITLE
Inconsistent definition of "alive host"

### ISSUE THREAD

**Issue by saladpanda** [jonny1102/nmap-parse#6]
I noticed your definition of an "alive host" varies throughout the tool.
Sometimes it's a host that nmap determined to be "up", sometimes it is a host that is "up" and has open ports.
This inconsistency is confusing.

**Comment by jonny1102** [comment]
Can you let me know where this differs so I can take a look?
I can't remember if this was a workaround to prevent output containing all hosts when an nmap scan is run with the -Pn flag.

**Comment by saladpanda** [comment]
Sure.

### Definition 1:
alive=up (according to nmap)
* the "only_alive" filter

### Definition 2:
alive=up + open ports
* "Alive hosts" in the Summary
* `-a` parameter
* `alive_hosts` interactive command 

I guess renaming "only_alive" to "only_up" and defining *alive* as being up and having ports would straighten the terminology and prevent confusion.

**Comment by jonny1102** [comment]
Finally got around to renaming it to only_up as suggested, thanks for the feedback
