### ISSUE TITLE
IPv6 issue

### ISSUE THREAD

**Issue by drwetter** [jonny1102/nmap-parse#9]
Hi,

thanks for the tool.

It hiccups on this.... umm.. err... brand new protocol IPv6

```
    self.parseNmapXmlFiles(xmlFiles)
    File "[REDACTED]/nmap-parse/modules/nmap.py", line 57, in parseNmapXmlFiles
    ip = xHost.find("address[@addrtype='ipv4']").get('addr')
```

Actually somebody I was scanning was really using this brand new protocol as I found out !!1!

\</sacarsm>

**Comment by jonny1102** [comment]
Thanks for the heads up.
Updated so it no longer hicups but will just ignore hosts without an ipv4 address now and warn you in the console output.
Maybe one day I will actually update it to handle ipv6 too

**Comment by drwetter** [comment]
Thanks.

I'll go ahead and open another issue for the implementation of IPv6. If not you, maybe somebody adds a PR.
